# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    -   id: ruff-check
    -   id: ruff-format

# pydocstyle
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ["--ignore=D100,D104,D203,D212"]

-   repo: local
    hooks:

    # sphinx
    -   id: docs-build
        name: Build Sphinx docs
        entry: bash -c "cd docs && make html"
        language: system
        files: '\.(py|rst)$'
        pass_filenames: false
        verbose: true

    # pytest
    -   id: pytest-check
        name: Run pytest
        entry: pytest
        language: system
        files: \.py$
        args:
          - --doctest-modules
          - -s
          - -vv
          - src
          - tests
        pass_filenames: false
        always_run: true
        verbose: true

    # coverage
    -   id: python-coverage
        name: Run coverage
        entry: pytest --cov=src tests
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
        verbose: true

    # build
    -   id: python-build
        name: Run build
        entry: python -m build
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
        verbose: true
