# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    -   id: ruff-check
    -   id: ruff-format

# pydocstyle
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ["--ignore=D100,D203,D212"]

# sphinx
-   repo: local
    hooks:
    -   id: docs-build
        name: Build Sphinx docs
        entry: bash -c "cd docs && make html"
        language: system
        files: '\.(py|rst)$'
        pass_filenames: false
